---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "fabra-sync"
  namespace: "default"
  labels:
    app: "fabra-sync"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "fabra-sync"
  template:
    metadata:
      labels:
        app: "fabra-sync"
    spec:
      containers:
      - name: "fabra-sync"
        image: "gcr.io/fabra-344902/sync:latest"
        resources:
          requests:
            cpu: "2000m"
            memory: "2Gi"
        env:
        - name: IS_PROD
          value: "true"

---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "fabra-sync-hpa-aykx"
  namespace: "default"
  labels:
    app: "fabra-sync"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "fabra-sync"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  annotations:
    iam.gke.io/gcp-service-account: "932264813910-compute@developer.gserviceaccount.com"
  name: "default"
  namespace: "default"
