ALTER TABLE listings ALTER COLUMN category DROP NOT NULL;
ALTER TABLE listings ALTER COLUMN location DROP NOT NULL;
ALTER TABLE listings ALTER COLUMN coordinates DROP NOT NULL;
ALTER TABLE listings ALTER COLUMN name DROP NOT NULL;
ALTER TABLE listings ALTER COLUMN description DROP NOT NULL;
ALTER TABLE listings ALTER COLUMN price DROP NOT NULL;
ALTER TABLE listings DROP COLUMN published;
ALTER TABLE listings ADD COLUMN status VARCHAR(64) DEFAULT 'published';
ALTER TABLE listings ALTER COLUMN status DROP DEFAULT;