ALTER TABLE listings DROP COLUMN IF EXISTS short_description;
ALTER TABLE listings DROP COLUMN IF EXISTS duration_hours;
ALTER TABLE listings DROP COLUMN IF EXISTS max_guests;
ALTER TABLE listings DROP COLUMN IF EXISTS cancellation;
ALTER TABLE listings DROP COLUMN IF EXISTS highlights;
ALTER TABLE listings DROP COLUMN IF EXISTS includes;

ALTER TABLE users DROP COLUMN IF EXISTS verified;
ALTER TABLE users DROP COLUMN IF EXISTS about;
ALTER TABLE users DROP COLUMN IF EXISTS first_name;
ALTER TABLE users DROP COLUMN IF EXISTS last_name;
ALTER TABLE users ADD COLUMN IF NOT EXISTS name VARCHAR(256);

ALTER TABLE listing_images DROP COLUMN IF EXISTS rank;