ALTER TABLE users ADD COLUMN login_method VARCHAR(32) NOT NULL DEFAULT 'google';
ALTER TABLE users ALTER COLUMN login_method DROP DEFAULT;
ALTER TABLE users ADD COLUMN hashed_password VARCHAR(64);
ALTER TABLE users ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users ALTER COLUMN email_verified DROP DEFAULT;