ALTER TABLE listings ALTER COLUMN category SET NOT NULL;
ALTER TABLE listings ALTER COLUMN location SET NOT NULL;
ALTER TABLE listings ALTER COLUMN coordinates SET NOT NULL;
ALTER TABLE listings ALTER COLUMN name SET NOT NULL;
ALTER TABLE listings ALTER COLUMN description SET NOT NULL;
ALTER TABLE listings ALTER COLUMN price SET NOT NULL;
ALTER TABLE listings DROP COLUMN status;
ALTER TABLE listings ADD COLUMN published BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE listings ALTER COLUMN published DROP DEFAULT;