ALTER TABLE listings ADD COLUMN short_description VARCHAR(256);
ALTER TABLE listings ADD COLUMN duration_hours SMALLINT;
ALTER TABLE listings ADD COLUMN max_guests SMALLINT;
ALTER TABLE listings ADD COLUMN cancellation VARCHAR(256) NOT NULL DEFAULT 'flexible';
ALTER TABLE listings ADD COLUMN highlights VARCHAR(80)[] NOT NULL DEFAULT '{}';
ALTER TABLE listings ADD COLUMN includes VARCHAR(80)[] NOT NULL DEFAULT '{}';
ALTER TABLE listings ALTER COLUMN cancellation DROP DEFAULT;
ALTER TABLE listings ALTER COLUMN highlights DROP DEFAULT;
ALTER TABLE listings ALTER COLUMN includes DROP DEFAULT;

ALTER TABLE users ADD COLUMN verified BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN about VARCHAR(512);
ALTER TABLE users ADD COLUMN first_name VARCHAR(128) NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN last_name VARCHAR(128) NOT NULL DEFAULT '';
ALTER TABLE users ALTER COLUMN first_name DROP DEFAULT;
ALTER TABLE users ALTER COLUMN last_name DROP DEFAULT;
ALTER TABLE users DROP COLUMN name;

ALTER TABLE listing_images ADD COLUMN rank SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE listing_images ALTER COLUMN rank DROP DEFAULT;