ALTER TABLE users ADD COLUMN IF NOT EXISTS currency VARCHAR(5) NOT NULL DEFAULT 'USD';
ALTER TABLE users ALTER COLUMN currency DROP DEFAULT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS commission_percent SMALLINT NOT NULL DEFAULT 15;
ALTER TABLE users ALTER COLUMN commission_percent DROP DEFAULT;

ALTER TABLE bookings ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE bookings DROP COLUMN IF EXISTS time_slot_id;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS start_time TIME WITH TIME ZONE;