ALTER TABLE listings ADD COLUMN city VARCHAR(512) NOT NULL DEFAULT '';
ALTER TABLE listings ADD COLUMN region VARCHAR(512) NOT NULL DEFAULT '';
ALTER TABLE listings ADD COLUMN country VARCHAR(512) NOT NULL DEFAULT '';
ALTER TABLE listings ADD COLUMN postal_code VARCHAR(64);

ALTER TABLE listings ALTER COLUMN city DROP DEFAULT;
ALTER TABLE listings ALTER COLUMN region DROP DEFAULT;
ALTER TABLE listings ALTER COLUMN country DROP DEFAULT;