ALTER TABLE listings DROP COLUMN IF EXISTS city;
ALTER TABLE listings DROP COLUMN IF EXISTS region;
ALTER TABLE listings DROP COLUMN IF EXISTS country;
ALTER TABLE listings DROP COLUMN IF EXISTS postal_code;