CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (first_name, last_name, email)
VALUES
--   ('John', 'Doe', 'john.doe@example.com'),
--   ('Jane', 'Smith', 'jane.smith@example.com'),
--   ('Jim', 'Williams', 'jim.williams@example.com'),
--   ('Jake', 'Miller', 'jake.miller@example.com'),
--   ('Jill', 'Brown', 'jill.brown@example.com'),
--   ('Jerry', 'Johnson', 'jerry.johnson@example.com'),
--   ('Janet', 'Davis', 'janet.davis@example.com'),
--   ('Jamie', 'Clark', 'jamie.clark@example.com'),
--   ('Jack', 'Anderson', 'jack.anderson@example.com'),
--   ('Jasmine', 'Taylor', 'jasmine.taylor@example.com'),
--   ('Mark', 'Smith', 'mark.smith@example.com'),
  ('Emily', 'Johnson', 'emily.johnson@example.com'),
  ('Michael', 'Brown', 'michael.brown@example.com'),
  ('Sarah', 'Davis', 'sarah.davis@example.com'),
  ('Christopher', 'Miller', 'christopher.miller@example.com'),
  ('Jessica', 'Anderson', 'jessica.anderson@example.com'),
  ('Matthew', 'Taylor', 'matthew.taylor@example.com'),
  ('Amanda', 'Clark', 'amanda.clark@example.com'),
  ('David', 'Anderson', 'david.anderson@example.com'),
  ('Ashley', 'Miller', 'ashley.miller@example.com'),
  ('Andrew', 'Clark', 'andrew.clark@example.com'),
  ('Stephanie', 'Taylor', 'stephanie.taylor@example.com'),
  ('Joshua', 'Brown', 'joshua.brown@example.com'),
  ('Nicole', 'Davis', 'nicole.davis@example.com'),
  ('Ryan', 'Johnson', 'ryan.johnson@example.com'),
  ('Lauren', 'Smith', 'lauren.smith@example.com'),
  ('Daniel', 'Miller', 'daniel.miller@example.com'),
  ('Kayla', 'Anderson', 'kayla.anderson@example.com'),
  ('Brandon', 'Taylor', 'brandon.taylor@example.com'),
  ('Megan', 'Clark', 'megan.clark@example.com'),
  ('William', 'Anderson', 'william.anderson@example.com'),
  ('Olivia', 'Miller', 'olivia.miller@example.com'),
  ('Jacob', 'Clark', 'jacob.clark@example.com'),
  ('Elizabeth', 'Taylor', 'elizabeth.taylor@example.com'),
  ('Tyler', 'Brown', 'tyler.brown@example.com'),
  ('Samantha', 'Davis', 'samantha.davis@example.com'),
  ('Nathan', 'Johnson', 'nathan.johnson@example.com'),
  ('Hannah', 'Smith', 'hannah.smith@example.com'),
  ('Joseph', 'Miller', 'joseph.miller@example.com'),
  ('Alexis', 'Anderson', 'alexis.anderson@example.com'),
  ('Christopher', 'Taylor', 'christopher.taylor@example.com'),
  ('Taylor', 'Clark', 'taylor.clark@example.com'),
  ('Abigail', 'Anderson', 'abigail.anderson@example.com'),
  ('Andrew', 'Miller', 'andrew.miller@example.com'),
  ('Victoria', 'Taylor', 'victoria.taylor@example.com'),
  ('James', 'Brown', 'james.brown@example.com'),
  ('Grace', 'Davis', 'grace.davis@example.com'),
  ('Logan', 'Johnson', 'logan.johnson@example.com'),
  ('Anna', 'Smith', 'anna.smith@example.com'),
  ('John', 'Anderson', 'john.anderson@example.com');
