steps:
- id: test-backend
  name: 'golang:1.18'
  entrypoint: /bin/bash
  args: ['ls']

- id: build-backend
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/fabra-344902/fabra:$COMMIT_SHA', '-t', 'gcr.io/fabra-344902/fabra:latest', 'backend/']
  waitFor: ['test-backend']

- id: push-backend
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/fabra-344902/fabra:latest']
  waitFor: ['build-backend']

- id: deploy-backend
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'fabra', '--image', 'gcr.io/fabra-344902/fabra:latest', '--region', 'us-west1', '--platform', 'managed']
  waitFor: ['push-backend']

images: ['gcr.io/fabra-344902/fabra:$COMMIT_SHA', 'gcr.io/fabra-344902/fabra:latest']
