steps:
- id: test-sync
  name: 'golang:1.18'
  script: |
    cd backend/sync;
    go test -v ./...;
  env:
    - 'IS_CLOUD_BUILD=true'
  waitFor: ['-']

- id: build-sync
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/fabra-344902/sync:$SHORT_SHA', '-f', 'backend/sync/Dockerfile', 'backend/']
  waitFor: ['test-sync']

- id: push-sync
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/fabra-344902/sync:$SHORT_SHA']
  waitFor: ['build-sync']

- id: deploy-sync
  name: "gcr.io/cloud-builders/gke-deploy"
  args: 
  - 'run'
  - '--filename=backend/sync/gke-deployment.yaml'
  - '--image=gcr.io/fabra-344902/sync:$SHORT_SHA'
  - '--location=us-west1'
  - '--cluster=fabra-sync-gke-cluster'
  waitFor: ['push-sync']

images: ['gcr.io/fabra-344902/sync:$SHORT_SHA']
